### PR TITLE
Add default trait and inline all short functions

### LINKED ISSUE #6: Inlining
Maybe it's good to add the inline hint to all short functions? This is done in objects similar to dual_num such as `num::Complex`.

### PR DESCRIPTION
**Pull request by benruijl**
Fixes #6 and #7.

### CODE REVIEW

**Comment by ChristopherRabotin** [comment]
I am on-board with these changes.

For the sake of regression testing, I would recommend simply adding a test
for Default. I am not aware of any way that we can test the in-line flags.

**Comment by benruijl** [comment]
I've added a test!

**Comment by ChristopherRabotin** [comment]
That was quick, thanks! I approve of these changes.

I'll let @novacrazy give his approval as well.

**Comment by novacrazy** [comment]
Yeah, this is fine. I'll go ahead and merge this, then publish a new minor release. Thanks, @benruijl!

**Pull request merged**
