### PR TITLE
use selfs where possible

### PR DESCRIPTION
**Pull request by adamnemecek**

### CODE REVIEW

**Comment by ChristopherRabotin** [comment]
Nice!

@novacrazy I can merge this in tonight and do a "patch" version bump. Does that sounds good to you?

**Comment by adamnemecek** [comment]
Sounds good!

**Comment by novacrazy** [comment]
Sorry, I was busy with personal projects yesterday.

I was going to say I'm not a fan of `Self` everywhere, especially for constructor methods. I like seeing `Dual<T>` in the docs for the return type when creating a value.

However, nothing is technically wrong with this.

**Comment by ChristopherRabotin** [comment]
@novacrazy Would you like me to revert that PR then?

**Comment by novacrazy** [comment]
No need, I redid this and settled on mostly `Self` for chained operations, and `Dual<T>` for creation/conversion operations.

**Pull request merged**
